Cleanups.
native-image-jfr/graal pull request #32
Opened 2021-05-20 13:45 UTC by christianhaeubl

I removed all TODOs from the sources. We should probably collect the TODOs listed below in a separate issue:
- Rewrite some of the Java-level JFR events as Native events (e.g., JavaThreadStatistics)
- JfrChunkWriter.openFile should probably write all live threads
- JfrNativeEventWriter.accommodate can lose the current event if the new buffer is null
- JfrThreadLocal.beforeThreadRun - parentThread is null at the moment
- JfrThreadLocal.beforeThreadRun - write a thread checkpoint so that JFR knows about the newly started thread
- JfrTypeRepository - fix the 'exported' field
- TestSingleEvent - parse & verify the constant pool

2021-05-20 13:46 UTC, christianhaeubl commented
Which command line do you currently use for executing the unit tests?

2021-05-20 13:49 UTC, jiekang commented
> Which command line do you currently use for executing the unit tests?

I think it's: `$ mx native-unittest com.oracle.svm.jfrtest --build-args -H:+AllowVMInspection`

2021-05-20 21:30 UTC, jiekang requested changes
One comment for `JfrGlobalMemory.shouldDiscard()`

There is also a failure on running atm with
```
No Java synchronization must be performed within a VMOperation: if the object is already locked, the VM is deadlocked
Fatal error: Should not reach here: Not okay to block.
```

Maybe after reworking on top of the chunk rotation that has the uninterruptible writes it'll be okay?

2021-05-20 21:30 UTC, jiekang commented on substratevm/src/com.oracle.svm.jfr/src/com/oracle/svm/jfr/JfrGlobalMemory.java
> +        VMError.unimplemented();
Looks like `VMError.unimplemented()` is not uninterruptible, so maybe temporarily set callee to be false?

2021-05-21 08:35 UTC, christianhaeubl commented
Rebased and fixed the remaining issues. The unit tests pass now.
@rkennke : it seems weird that the method `JfrTraceIdLoadBarrier.clear()` is currently unused. Please have a brief look on that.

2021-05-21 20:18 UTC, jiekang approved these changes

2021-05-22 17:04 UTC, merged

2021-05-25 15:16 UTC, rkennke commented
> Rebased and fixed the remaining issues. The unit tests pass now.
> @rkennke : it seems weird that the method `JfrTraceIdLoadBarrier.clear()` is currently unused. Please have a brief look on that.

Yeah I guess it should be called right after epoch switch.